@token = 6438198f-437a-4119-ba3f-13cacd5e28ef
@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###
DELETE {{baseUrl}}/testing

###
POST {{baseUrl}}/testing/users
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "name": "Test User"
}
